package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SubProject1_SubProjectNest3_SubProjectNest3BuildConfig'
in the project with id = 'SubProject1_SubProjectNest3', and delete the patch script.
*/
create(RelativeId("SubProject1_SubProjectNest3"), BuildType({
    id("SubProject1_SubProjectNest3_SubProjectNest3BuildConfig")
    name = "SubProjectNest3_BuildConfig"
    description = "BuildConfig_SubProjectNest3"
}))

