package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the project with id = 'SubProject1_SubProjectNest2'
from your code, and delete the patch script.
*/
deleteProject(RelativeId("SubProject1_SubProjectNest2"))

